import { Zen_Dots } from "next/font/google";
import "./globals.css";
import Providers from "@/utils/Providers";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Background from "@/components/global/Background";

const zen = Zen_Dots({ subsets: ["latin"], weight: ['400'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={zen.className + " w-screen h-screen overflow-hidden "}>
        <Providers>
          <ToastContainer />
          <Background/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
